/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rock88dev_alynx_ALynxEmuProxy */

#ifndef _Included_com_rock88dev_alynx_ALynxEmuProxy
#define _Included_com_rock88dev_alynx_ALynxEmuProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rock88dev_alynx_ALynxEmuProxy
 * Method:    AL_Check_BIOS
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rock88dev_alynx_ALynxEmuProxy_AL_1Check_1BIOS
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rock88dev_alynx_ALynxEmuProxy
 * Method:    AL_Set_Rom_Path
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rock88dev_alynx_ALynxEmuProxy_AL_1Set_1Rom_1Path
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rock88dev_alynx_ALynxEmuProxy
 * Method:    AL_Rotation_Get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rock88dev_alynx_ALynxEmuProxy_AL_1Rotation_1Get
  (JNIEnv *, jclass);

/*
 * Class:     com_rock88dev_alynx_ALynxEmuProxy
 * Method:    AL_Emu_Run
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rock88dev_alynx_ALynxEmuProxy_AL_1Emu_1Run
  (JNIEnv *, jclass);

/*
 * Class:     com_rock88dev_alynx_ALynxEmuProxy
 * Method:    AL_Emu_Stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rock88dev_alynx_ALynxEmuProxy_AL_1Emu_1Stop
  (JNIEnv *, jclass);

/*
 * Class:     com_rock88dev_alynx_ALynxEmuProxy
 * Method:    AL_Emu_Pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rock88dev_alynx_ALynxEmuProxy_AL_1Emu_1Pause
  (JNIEnv *, jclass);

/*
 * Class:     com_rock88dev_alynx_ALynxEmuProxy
 * Method:    AL_Emu_Resume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rock88dev_alynx_ALynxEmuProxy_AL_1Emu_1Resume
  (JNIEnv *, jclass);

/*
 * Class:     com_rock88dev_alynx_ALynxEmuProxy
 * Method:    AL_Image_Get_Width
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rock88dev_alynx_ALynxEmuProxy_AL_1Image_1Get_1Width
  (JNIEnv *, jclass);

/*
 * Class:     com_rock88dev_alynx_ALynxEmuProxy
 * Method:    AL_Image_Get_Height
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rock88dev_alynx_ALynxEmuProxy_AL_1Image_1Get_1Height
  (JNIEnv *, jclass);

/*
 * Class:     com_rock88dev_alynx_ALynxEmuProxy
 * Method:    AL_Image_Get_Buffer
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_com_rock88dev_alynx_ALynxEmuProxy_AL_1Image_1Get_1Buffer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_rock88dev_alynx_ALynxEmuProxy
 * Method:    AL_Key_Down
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rock88dev_alynx_ALynxEmuProxy_AL_1Key_1Down
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rock88dev_alynx_ALynxEmuProxy
 * Method:    AL_Key_Up
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rock88dev_alynx_ALynxEmuProxy_AL_1Key_1Up
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rock88dev_alynx_ALynxEmuProxy
 * Method:    AL_Save_State
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rock88dev_alynx_ALynxEmuProxy_AL_1Save_1State
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rock88dev_alynx_ALynxEmuProxy
 * Method:    AL_Load_State
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rock88dev_alynx_ALynxEmuProxy_AL_1Load_1State
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rock88dev_alynx_ALynxEmuProxy
 * Method:    AL_Emu_Set_Config
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_rock88dev_alynx_ALynxEmuProxy_AL_1Emu_1Set_1Config
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_rock88dev_alynx_ALynxEmuProxy
 * Method:    AL_Emu_Get_FPS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rock88dev_alynx_ALynxEmuProxy_AL_1Emu_1Get_1FPS
  (JNIEnv *, jclass);

/*
 * Class:     com_rock88dev_alynx_ALynxEmuProxy
 * Method:    AL_GL_NativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rock88dev_alynx_ALynxEmuProxy_AL_1GL_1NativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_rock88dev_alynx_ALynxEmuProxy
 * Method:    AL_GL_NativeDeinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rock88dev_alynx_ALynxEmuProxy_AL_1GL_1NativeDeinit
  (JNIEnv *, jclass);

/*
 * Class:     com_rock88dev_alynx_ALynxEmuProxy
 * Method:    AL_GL_NativeRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rock88dev_alynx_ALynxEmuProxy_AL_1GL_1NativeRender
  (JNIEnv *, jclass);

/*
 * Class:     com_rock88dev_alynx_ALynxEmuProxy
 * Method:    AL_GL_NativeSetConfig
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rock88dev_alynx_ALynxEmuProxy_AL_1GL_1NativeSetConfig
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_rock88dev_alynx_ALynxEmuProxy
 * Method:    AL_GL_NativeSetScreenRect
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_rock88dev_alynx_ALynxEmuProxy_AL_1GL_1NativeSetScreenRect
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_rock88dev_alynx_ALynxEmuProxy
 * Method:    AL_GL_NativeSetRenderRect
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_rock88dev_alynx_ALynxEmuProxy_AL_1GL_1NativeSetRenderRect
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_rock88dev_alynx_ALynxEmuProxy
 * Method:    AL_GL_NativeLoadTex
 * Signature: (IIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_com_rock88dev_alynx_ALynxEmuProxy_AL_1GL_1NativeLoadTex
  (JNIEnv *, jclass, jint, jint, jint, jobject, jint);

/*
 * Class:     com_rock88dev_alynx_ALynxEmuProxy
 * Method:    AL_GL_NativeSetButton
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_rock88dev_alynx_ALynxEmuProxy_AL_1GL_1NativeSetButton
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
